/**
 *
 *  Role.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */
// NOLINTBEGIN
#include "Role.h"

#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::famy_account;

const std::string Role::Cols::_id = "id";
const std::string Role::Cols::_description = "description";
const std::string Role::primaryKeyName = "id";
const bool Role::hasPrimaryKey = true;
const std::string Role::tableName = "role";

const std::vector<typename Role::MetaData> Role::metaData_ = {
  {         "id",     "int64_t",            "bigint",   8, 1, 1, 1},
  {"description", "std::string", "character varying", 200, 0, 0, 1}
};

const std::string&
Role::getColumnName(size_t index) noexcept(false)
{
  assert(index < metaData_.size());
  return metaData_ [index].colName_;
}

Role::Role(const Row& r, const ssize_t indexOffset) noexcept
{
  if(indexOffset < 0)
  {
    if(! r ["id"].isNull())
    {
      id_ = std::make_shared<int64_t>(r ["id"].as<int64_t>());
    }
    if(! r ["description"].isNull())
    {
      description_ =
        std::make_shared<std::string>(r ["description"].as<std::string>());
    }
  }
  else
  {
    size_t offset = (size_t)indexOffset;
    if(offset + 2 > r.size())
    {
      LOG_FATAL << "Invalid SQL result for this model";
      return;
    }
    size_t index;
    index = offset + 0;
    if(! r [index].isNull())
    {
      id_ = std::make_shared<int64_t>(r [index].as<int64_t>());
    }
    index = offset + 1;
    if(! r [index].isNull())
    {
      description_ = std::make_shared<std::string>(r [index].as<std::string>());
    }
  }
}

Role::Role(
  const Json::Value& pJson,
  const std::vector<std::string>& pMasqueradingVector
) noexcept(false)
{
  if(pMasqueradingVector.size() != 2)
  {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if(! pMasqueradingVector [0].empty() && pJson.isMember(pMasqueradingVector [0]))
  {
    dirtyFlag_ [0] = true;
    if(! pJson [pMasqueradingVector [0]].isNull())
    {
      id_ = std::make_shared<int64_t>(
        (int64_t)pJson [pMasqueradingVector [0]].asInt64()
      );
    }
  }
  if(! pMasqueradingVector [1].empty() && pJson.isMember(pMasqueradingVector [1]))
  {
    dirtyFlag_ [1] = true;
    if(! pJson [pMasqueradingVector [1]].isNull())
    {
      description_ =
        std::make_shared<std::string>(pJson [pMasqueradingVector [1]].asString()
        );
    }
  }
}

Role::Role(const Json::Value& pJson) noexcept(false)
{
  if(pJson.isMember("id"))
  {
    dirtyFlag_ [0] = true;
    if(! pJson ["id"].isNull())
    {
      id_ = std::make_shared<int64_t>((int64_t)pJson ["id"].asInt64());
    }
  }
  if(pJson.isMember("description"))
  {
    dirtyFlag_ [1] = true;
    if(! pJson ["description"].isNull())
    {
      description_ =
        std::make_shared<std::string>(pJson ["description"].asString());
    }
  }
}

void
Role::updateByMasqueradedJson(
  const Json::Value& pJson,
  const std::vector<std::string>& pMasqueradingVector
) noexcept(false)
{
  if(pMasqueradingVector.size() != 2)
  {
    LOG_ERROR << "Bad masquerading vector";
    return;
  }
  if(! pMasqueradingVector [0].empty() && pJson.isMember(pMasqueradingVector [0]))
  {
    if(! pJson [pMasqueradingVector [0]].isNull())
    {
      id_ = std::make_shared<int64_t>(
        (int64_t)pJson [pMasqueradingVector [0]].asInt64()
      );
    }
  }
  if(! pMasqueradingVector [1].empty() && pJson.isMember(pMasqueradingVector [1]))
  {
    dirtyFlag_ [1] = true;
    if(! pJson [pMasqueradingVector [1]].isNull())
    {
      description_ =
        std::make_shared<std::string>(pJson [pMasqueradingVector [1]].asString()
        );
    }
  }
}

void
Role::updateByJson(const Json::Value& pJson) noexcept(false)
{
  if(pJson.isMember("id"))
  {
    if(! pJson ["id"].isNull())
    {
      id_ = std::make_shared<int64_t>((int64_t)pJson ["id"].asInt64());
    }
  }
  if(pJson.isMember("description"))
  {
    dirtyFlag_ [1] = true;
    if(! pJson ["description"].isNull())
    {
      description_ =
        std::make_shared<std::string>(pJson ["description"].asString());
    }
  }
}

const int64_t&
Role::getValueOfId() const noexcept
{
  const static int64_t defaultValue = int64_t();
  if(id_)
  {
    return *id_;
  }
  return defaultValue;
}

const std::shared_ptr<int64_t>&
Role::getId() const noexcept
{
  return id_;
}

void
Role::setId(const int64_t& pId) noexcept
{
  id_ = std::make_shared<int64_t>(pId);
  dirtyFlag_ [0] = true;
}

const typename Role::PrimaryKeyType&
Role::getPrimaryKey() const
{
  assert(id_);
  return *id_;
}

const std::string&
Role::getValueOfDescription() const noexcept
{
  const static std::string defaultValue = std::string();
  if(description_)
  {
    return *description_;
  }
  return defaultValue;
}

const std::shared_ptr<std::string>&
Role::getDescription() const noexcept
{
  return description_;
}

void
Role::setDescription(const std::string& pDescription) noexcept
{
  description_ = std::make_shared<std::string>(pDescription);
  dirtyFlag_ [1] = true;
}

void
Role::setDescription(std::string&& pDescription) noexcept
{
  description_ = std::make_shared<std::string>(std::move(pDescription));
  dirtyFlag_ [1] = true;
}

void
Role::updateId(const uint64_t id)
{
}

const std::vector<std::string>&
Role::insertColumns() noexcept
{
  static const std::vector<std::string> inCols = {"description"};
  return inCols;
}

void
Role::outputArgs(drogon::orm::internal::SqlBinder& binder) const
{
  if(dirtyFlag_ [1])
  {
    if(getDescription())
    {
      binder << getValueOfDescription();
    }
    else
    {
      binder << nullptr;
    }
  }
}

const std::vector<std::string>
Role::updateColumns() const
{
  std::vector<std::string> ret;
  if(dirtyFlag_ [1])
  {
    ret.push_back(getColumnName(1));
  }
  return ret;
}

void
Role::updateArgs(drogon::orm::internal::SqlBinder& binder) const
{
  if(dirtyFlag_ [1])
  {
    if(getDescription())
    {
      binder << getValueOfDescription();
    }
    else
    {
      binder << nullptr;
    }
  }
}

Json::Value
Role::toJson() const
{
  Json::Value ret;
  if(getId())
  {
    ret ["id"] = (Json::Int64)getValueOfId();
  }
  else
  {
    ret ["id"] = Json::Value();
  }
  if(getDescription())
  {
    ret ["description"] = getValueOfDescription();
  }
  else
  {
    ret ["description"] = Json::Value();
  }
  return ret;
}

Json::Value
Role::toMasqueradedJson(const std::vector<std::string>& pMasqueradingVector
) const
{
  Json::Value ret;
  if(pMasqueradingVector.size() == 2)
  {
    if(! pMasqueradingVector [0].empty())
    {
      if(getId())
      {
        ret [pMasqueradingVector [0]] = (Json::Int64)getValueOfId();
      }
      else
      {
        ret [pMasqueradingVector [0]] = Json::Value();
      }
    }
    if(! pMasqueradingVector [1].empty())
    {
      if(getDescription())
      {
        ret [pMasqueradingVector [1]] = getValueOfDescription();
      }
      else
      {
        ret [pMasqueradingVector [1]] = Json::Value();
      }
    }
    return ret;
  }
  LOG_ERROR << "Masquerade failed";
  if(getId())
  {
    ret ["id"] = (Json::Int64)getValueOfId();
  }
  else
  {
    ret ["id"] = Json::Value();
  }
  if(getDescription())
  {
    ret ["description"] = getValueOfDescription();
  }
  else
  {
    ret ["description"] = Json::Value();
  }
  return ret;
}

bool
Role::validateJsonForCreation(const Json::Value& pJson, std::string& err)
{
  if(pJson.isMember("id"))
  {
    if(! validJsonOfField(0, "id", pJson ["id"], err, true))
    {
      return false;
    }
  }
  if(pJson.isMember("description"))
  {
    if(! validJsonOfField(1, "description", pJson ["description"], err, true))
    {
      return false;
    }
  }
  else
  {
    err = "The description column cannot be null";
    return false;
  }
  return true;
}

bool
Role::validateMasqueradedJsonForCreation(
  const Json::Value& pJson,
  const std::vector<std::string>& pMasqueradingVector,
  std::string& err
)
{
  if(pMasqueradingVector.size() != 2)
  {
    err = "Bad masquerading vector";
    return false;
  }
  try
  {
    if(! pMasqueradingVector [0].empty())
    {
      if(pJson.isMember(pMasqueradingVector [0]))
      {
        if(! validJsonOfField(
             0,
             pMasqueradingVector [0],
             pJson [pMasqueradingVector [0]],
             err,
             true
           ))
        {
          return false;
        }
      }
    }
    if(! pMasqueradingVector [1].empty())
    {
      if(pJson.isMember(pMasqueradingVector [1]))
      {
        if(! validJsonOfField(
             1,
             pMasqueradingVector [1],
             pJson [pMasqueradingVector [1]],
             err,
             true
           ))
        {
          return false;
        }
      }
      else
      {
        err = "The " + pMasqueradingVector [1] + " column cannot be null";
        return false;
      }
    }
  }
  catch(const Json::LogicError& e)
  {
    err = e.what();
    return false;
  }
  return true;
}

bool
Role::validateJsonForUpdate(const Json::Value& pJson, std::string& err)
{
  if(pJson.isMember("id"))
  {
    if(! validJsonOfField(0, "id", pJson ["id"], err, false))
    {
      return false;
    }
  }
  else
  {
    err = "The value of primary key must be set in the json object for update";
    return false;
  }
  if(pJson.isMember("description"))
  {
    if(! validJsonOfField(1, "description", pJson ["description"], err, false))
    {
      return false;
    }
  }
  return true;
}

bool
Role::validateMasqueradedJsonForUpdate(
  const Json::Value& pJson,
  const std::vector<std::string>& pMasqueradingVector,
  std::string& err
)
{
  if(pMasqueradingVector.size() != 2)
  {
    err = "Bad masquerading vector";
    return false;
  }
  try
  {
    if(! pMasqueradingVector [0].empty() && pJson.isMember(pMasqueradingVector [0]))
    {
      if(! validJsonOfField(
           0,
           pMasqueradingVector [0],
           pJson [pMasqueradingVector [0]],
           err,
           false
         ))
      {
        return false;
      }
    }
    else
    {
      err =
        "The value of primary key must be set in the json object for update";
      return false;
    }
    if(! pMasqueradingVector [1].empty() && pJson.isMember(pMasqueradingVector [1]))
    {
      if(! validJsonOfField(
           1,
           pMasqueradingVector [1],
           pJson [pMasqueradingVector [1]],
           err,
           false
         ))
      {
        return false;
      }
    }
  }
  catch(const Json::LogicError& e)
  {
    err = e.what();
    return false;
  }
  return true;
}

bool
Role::validJsonOfField(
  size_t index,
  const std::string& fieldName,
  const Json::Value& pJson,
  std::string& err,
  bool isForCreation
)
{
  switch(index)
  {
    case 0:
      if(pJson.isNull())
      {
        err = "The " + fieldName + " column cannot be null";
        return false;
      }
      if(isForCreation)
      {
        err = "The automatic primary key cannot be set";
        return false;
      }
      if(! pJson.isInt64())
      {
        err = "Type error in the " + fieldName + " field";
        return false;
      }
      break;
    case 1:
      if(pJson.isNull())
      {
        err = "The " + fieldName + " column cannot be null";
        return false;
      }
      if(! pJson.isString())
      {
        err = "Type error in the " + fieldName + " field";
        return false;
      }
      // asString().length() creates a string object, is there any better way to
      // validate the length?
      if(pJson.isString() && pJson.asString().length() > 200)
      {
        err = "String length exceeds limit for the " + fieldName +
              " field (the maximum value is 200)";
        return false;
      }

      break;
    default:
      err = "Internal error in the server";
      return false;
  }
  return true;
}

// NOLINTEND