if(NOT THIRDPARTY_DIR)
  set(THIRDPARTY_DIR "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty")
  message(STATUS "Setting third party directory was not specified. Setted to ${THIRDPARTY_DIR}")
  set(VCPKG_INSTALLED_DIR "${THIRDPARTY_DIR}")
endif()
if(NOT CMAKE_TOOLCHAIN_FILE)
  set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_SOURCE_DIR}/../vcpkg/scripts/buildsystems/vcpkg.cmake" CACHE STRING "Vcpkg toolchain file")
  message(STATUS "Setting toolchain file was not specified. Setted to ${CMAKE_TOOLCHAIN_FILE}")
endif()
if(NOT CMAKE_RUNTIME_OUTPUT_DIRECTORY)
  set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/bin")
  message(STATUS "Setting binary directory was not specified. Setted to ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
endif()
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
if(NOT DOCKER_ID)
  set(DOCKER_ID thelingeringwill)
  message(STATUS "setting docker id was not specified. Setted to ${DOCKER_ID}")
endif()
if(NOT DOCKER_REPO)
  set(DOCKER_REPO simple-auth-jwt)
  message(STATUS "Setting docker repository was not specified. Setted to ${DOCKER_REPO}")
endif()
if(NOT DOCKER_TAG)
  set(DOCKER_TAG auth)
  message(STATUS "setting docker tag was not specified. Setted to ${DOCKER_TAG}")
endif()

