apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "account.fullname" . }}-virtualservice
spec:
  hosts:
  - "*"
  gateways:
  - gateway
  http:
  - match:
    - uri:
        prefix: {{ .Values.virtualService.uriPrefix }}
    rewrite:
      uri: /
    route:
    - destination:
        port:
          number: 80
        host: {{ include "account.fullname" . }}-service.default.svc.cluster.local
